### ISSUE TITLE
ip2region.db 使用byte数组构建的构造方法一直报错

### ISSUE THREAD

**Issue by G-H-Tao** [lionsoul2014/ip2region#150]
String dbPath = IpUtil.class.getResource("/ip2region.db").getPath();
DbSearcher searcher = new DbSearcher(config, getBytes(dbPath));
 private static byte[] getBytes(String filePath){
        byte[] buffer = null;
        try {
            File file = new File(filePath);
            FileInputStream fis = new FileInputStream(file);
            ByteArrayOutputStream bos = new ByteArrayOutputStream(1000);
            byte[] b = new byte[1000];
            int n;
            while ((n = fis.read(b)) != -1) {
                bos.write(b, 0, n);
            }
            fis.close();
            bos.close();
            buffer = bos.toByteArray();
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }
        return buffer;
    }

**Comment by G-H-Tao** [comment]
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.prisight.util.IpUtil.getCityInfo(IpUtil.java:94)
	at com.prisight.pc.service.impl.LoginServiceImpl.main(LoginServiceImpl.java:271)
Caused by: java.lang.NullPointerException
	at org.lionsoul.ip2region.DbSearcher.btreeSearch(DbSearcher.java:182)
	at org.lionsoul.ip2region.DbSearcher.btreeSearch(DbSearcher.java:309)
	... 6 more
null

**Comment by lionsoul2014** [comment]
注意两点：
1，使用byte[]方式构造DbSearcher就直接使用memorySearch查询，不要使用btree或者binary查询了。
2，确保你传入的byte[]是正确的。
