### ISSUE TITLE
README文档描述有误，具体在”ip2region.db的生成“第4点

### ISSUE THREAD

**Issue by ChanaLii** [lionsoul2014/ip2region#162]
#原文执行路径如下：
```
➜ cd ${ip2region_root}/java/
➜ java -jar dbMaker-1.2.2.jar -src ./data/ip.merge.txt -region ./data/global_region.csv

java.io.IOException: Error: Invalid file path ./data/ip.merge.txt
	at org.lionsoul.ip2region.DbMaker.<init>(Unknown Source)
	at org.lionsoul.ip2region.DbMaker.main(Unknown Source)
```

#正确执行路径应为：
```
➜ cd ${ip2region_root}/java/
➜ java -jar dbMaker-1.2.2.jar -src ../../data/ip.merge.txt -region ../../data/global_region.csv -dst ../../data/
```
![image](https://user-images.githubusercontent.com/20842481/90303545-50a1a480-dee1-11ea-892d-1acce0192f0f.png)

#问题发生的原因是打包的目录层级发生了变化

**Comment by lionsoul2014** [comment]
感谢反馈，可以提交一个pr
