### ISSUE TITLE
python2 xdbSearch 报错

### ISSUE THREAD

**Issue by reesezxf** [lionsoul2014/ip2region#265]
Python2.7.18 运行 /binding/python/xdbSearcher.py 查询IP报错，Python3 运行正常
报错信息
`Traceback (most recent call last):
  File "/home/zz/workspace/PycharmProjects/tt/test_ip/xdbSearcher.py", line 204, in <module>
    region_str = searcher.searchByIPStr(ip)
  File "/home/zz/workspace/PycharmProjects/tt/test_ip/xdbSearcher.py", line 79, in searchByIPStr
    return self.searchByIPLong(ip)
  File "/home/zz/workspace/PycharmProjects/tt/test_ip/xdbSearcher.py", line 117, in searchByIPLong
    dataLen = self.getInt2(buffer_sip, 8)
  File "/home/zz/workspace/PycharmProjects/tt/test_ip/xdbSearcher.py", line 179, in getInt2
    return ((b[offset] & 0x000000FF) | (b[offset + 1] & 0x0000FF00))
TypeError: unsupported operand type(s) for &: 'str' and 'int'`

初步查看应该是：loadContentFromFile这个function，Python2 的io.open(dbfile) 读取到的是 乱码
`@staticmethod
    def loadContentFromFile(dbfile):
        try:
            f = io.open(dbfile, "rb")
            all_data = f.read()
            f.close()
            return all_data
        except IOError as e:
            print("[Error]: %s" % e)`
先记录下，试了几个方法读取 xdb文件 都是乱码

**Comment by lionsoul2014** [comment]
这个 binding 是适用 python3 的，python2 不兼容
